- name: Install Snort v2
  hosts: snort_debian

  pre_tasks:
    - name: Update apt cache if it's needed.
      become: true
      apt:
        update_cache: true
        upgrade: true
        autoremove: true

  tasks:
    - name: Install Snort.
      become: true
      apt:
        name: snort

    - name: Check if eth0 is on promiscuous mode.
      become: true
      shell:
        cmd: "ifconfig eth0 | grep 'PROMISC'"
      ignore_errors: true
      no_log: true
      changed_when: false
      register: eth0_promisc_query

    - name: Enable promiscuous mode on primary eth0 interface.
      become: true
      shell:
        cmd: ifconfig eth0 promisc
      when: "eth0_promisc_query.rc != 0"

    - name: Copy Snort configuration and rules to remote.
      become: true
      copy:
        src: snort/
        dest: /etc/snort/
