- name: Install Snort v2
  hosts: snort_debian
  pre_tasks:
    - name: Update apt cache if it's needed.
      become: true
      apt:
        update_cache: true
        upgrade: true
        cache_valid_time: 86400
